[package]
name = "macos-automation"
version = "0.1.0"
edition = "2024"
description = "macOS 菜单栏自动化工具"

[dependencies]
objc2 = "0.6.2"
objc2-app-kit = "0.3.2"
objc2-core-bluetooth = { version = "0.3.2", default-features = false, features = ["CBCentralManager", "CBManager"] }
objc2-core-foundation = { version = "0.3.2", default-features = false, features = ["CFNumber", "CFPreferences", "CFString"] }
objc2-core-wlan = "0.3.2"
objc2-foundation = "0.3.2"

[package.metadata.bundle]
name = "MacOS Automation"
identifier = "com.thousanddream.macos-automation"
category = "public.app-category.utilities"
osx_info_plist_exts = ["Info.plist.ext"]
